ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY ./dist/awecloud-socks-$TARGETOS-$TARGETARCH /usr/bin/awecloud-socks
COPY ./.beagle/config.json /etc/awecloud-socks/config.json

RUN set -ex \
	&& apk add --no-cache openssl \
	&& mkdir -p /etc/awecloud-socks /usr/local/share/v2ray /var/log/v2ray

ENTRYPOINT ["/usr/bin/awecloud-socks","run","-c","/etc/awecloud-socks/config.json"]